!
! FRR Configuration for r-as100 (AS100)
!
hostname r-as100
password zebra
enable password zebra
!
interface eth1
  ip address 192.168.10.1/24
!
interface eth2
  ip address 100.64.0.1/30
!
line vty
!
router bgp 100
  bgp router-id 100.64.0.1
  no bgp ebgp-requires-policy
  neighbor 100.64.0.2 remote-as 200
  !
  address-family ipv4 unicast
    network 192.168.10.0/24
  exit-address-family
!
