!
! FRR Configuration for r-isp-b (AS400 — ISP B transit/backup)
!
hostname r-isp-b
password zebra
enable password zebra
!
interface eth1
  ip address 100.64.2.2/30
!
interface eth2
  ip address 100.64.4.1/30
!
line vty
!
router bgp 400
  bgp router-id 100.64.2.2
  no bgp ebgp-requires-policy
  neighbor 100.64.2.1 remote-as 100
  neighbor 100.64.4.2 remote-as 300
!
