role readonly
   5 permit command enable
   10 permit command sh(ow)? run.*
   20 permit command show .*
   30 permit command terminal .*
   40 permit command exit
   55 deny command .*
exit

username netconsole privilege 15 role network-admin secret phae0Phei4aex
username readonly privilege 15 role readonly secret Netconsole123
aaa authorization commands all default local