!
! FRR Configuration for r-dc (AS300 — Data Center router)
!
hostname r-dc
password zebra
enable password zebra
!
interface eth1
  ip address 100.64.3.2/30
!
interface eth2
  ip address 100.64.4.2/30
!
interface eth3
  ip address 192.168.200.1/24
!
line vty
!
router bgp 300
  bgp router-id 100.64.3.2
  no bgp ebgp-requires-policy
  neighbor 100.64.3.1 remote-as 200
  neighbor 100.64.4.1 remote-as 400
  !
  address-family ipv4 unicast
    network 192.168.200.0/24
  exit-address-family
!
